### ISSUE TITLE
Graph scales do not match on `/Reviewers`

### ISSUE THREAD

**Issue by SamWilsn** [Avarch-org/EIPsInsight#104]
**Describe the bug**

Because all the graphs autoscale to their data, it is impossible to compare quickly between graphs.

**Expected behavior**

The vertical and horizontal axis should have the same range for all the editor graphs.

**Screenshots**

![Screenshot_20241212-134213_Firefox](https://github.com/user-attachments/assets/519fb7c0-f954-4fca-84b7-a7e7154cbb5f)

**Comment by viwinkumarpadala** [comment]
Hello @SamWilsn, Thanks for raising the issue, we will work on the issue and update as soon as possible.

**Comment by EtherWorldCo** [comment]
I had the same concer, thanks for sharing, @SamWilsn !

**Comment by viwinkumarpadala** [comment]
Hello @SamWilsn , we have modified the chart to have a equal scale for all, please check it out again, and let us know if there are any issues further with that. 
**Screenshot**:
![image](https://github.com/user-attachments/assets/acfb1aae-da02-4eb1-85be-58ee56496158)

**Comment by SamWilsn** [comment]
The X-axis doesn't seem to line up:

![Screenshot_20241216-110135_Firefox (1)](https://github.com/user-attachments/assets/85e8d7a7-6db5-40c4-a831-3980bcde4ae5)

The rightmost point is 2024 vs. 2022 in this example.

**Comment by viwinkumarpadala** [comment]
Hey @SamWilsn , We have modified it such that all the charts will have the same timeline(x-axis). Please check it again on the website. 
**Screenshot for reference**:
![image](https://github.com/user-attachments/assets/7204ce1a-6756-4eea-ab33-dd18b3ace987)

**Comment by SamWilsn** [comment]
Looks good to me!
