### ISSUE TITLE
Active Editors Timeline Scatterplot hard to read

### ISSUE THREAD

**Issue by SamWilsn** [Avarch-org/EIPsInsight#105]
**Describe the bug**

The white border on the circles stacks over other circles, obscuring the color.

**Screenshots**

![Screenshot_20241212-134916_Firefox](https://github.com/user-attachments/assets/d94db66e-806f-4404-8d19-c8bfbede599e)

**Comment by viwinkumarpadala** [comment]
Hello @SamWilsn, Thanks for raising the issue, we will work on the issue and update as soon as possible.

**Comment by viwinkumarpadala** [comment]
Hey @SamWilsn , we have removed the white border of circles for better visibility, and also we will add a slider as well, for a better view. 
let us know if there are any issues further.
here is a screenshot of the update:
![image](https://github.com/user-attachments/assets/f74e564f-bde1-4459-b4f3-9fbebabed065)

**Comment by SamWilsn** [comment]
Looks great!

**Comment by viwinkumarpadala** [comment]
Hey @SamWilsn Just wanted to let you know, we have added a slider for this, like we discussed above.
![image](https://github.com/user-attachments/assets/38e567af-d7d1-414f-a42b-ba06b7c0bfff)
