### ISSUE TITLE
EIPSInsights meeting 19th August 2024

### ISSUE THREAD

**Issue by viwinkumarpadala** [Avarch-org/EIPsInsight#43]
TO-DOs
- [x] #61
- [x]  Network Upgrade issue is still pending. with [PR ](https://github.com/AvarchLLC/EIPsInsight/pull/45)
- [x]  Update the reports for pectra upgrade download file with [PR ](https://github.com/AvarchLLC/EIPsInsight/pull/45)
- [x]  Fix the text for meta eips with [PR ](https://github.com/AvarchLLC/EIPsInsight/pull/45)
- [x]  Update the arrow for status timeline with [PR ](https://github.com/AvarchLLC/EIPsInsight/pull/45)

**Comment by EtherWorldCo** [comment]
Aug 22, 2024

- [x] Create tabs for Issues and PRs on the same page
By default it should display a line chart from day 1 till date.

It could also include
- [x] option to select date range like we have for Monthly insight

**Comment by viwinkumarpadala** [comment]
Aug 22 2024
TO-DOs
- [ ]  ~~Design the correct queries for editors review(ex: pr 500, close is not captured)~~
- [ ]  ~~When the github handle is blank show the prs between the date range~~
- [x]  Update the UI chart for date vs pr  [PR ](https://github.com/AvarchLLC/EIPsInsight/pull/50)
- [x]  Per month Insights for editors review  [PR ](https://github.com/AvarchLLC/EIPsInsight/pull/50)
- [x]  If the data is not available then show the message No eip found with this number. with [PR ](https://github.com/AvarchLLC/EIPsInsight/pull/45)
- [x]  Update the UI timeline for order with [PR ](https://github.com/AvarchLLC/EIPsInsight/pull/45)
- [x]  Add functionality: Find a bug report here.  [PR ](https://github.com/AvarchLLC/EIPsInsight/pull/48)
