### ISSUE TITLE
Broken pages/links

### ISSUE THREAD

**Issue by hanniabu** [Avarch-org/EIPsInsight#53]
- Type page does not exist https://eipsinsight.com/type
- The Status page (via footer link) only loads the footer, there's no content
- If on the Status page, the footer links don't load the pages (but url updates)

**Comment by viwinkumarpadala** [comment]
Hey @hanniabu ! 👋

- The **type** page no longer exists as we’ve consolidated its content into the [/all](https://eipsinsight.com/all) page. We've also removed the old link from the footer to avoid confusion.
- The **status** page bug has been fixed, and the page is now visible! 🎉 (Note: There might still be some minor issues with this page, but we’re working on a clearer update which also includes self-explanatory texts in our next PR to improve the experience).

Please check out our website and let us know if it is clear or if we need to update anything.

Thanks again for flagging this bug! 🙏 We really appreciate your contribution. Please continue to share feedback and help us make the website even better! 🚀.
