### ISSUE TITLE
Add trend line to `/Analytics`

### ISSUE THREAD

**Issue by SamWilsn** [Avarch-org/EIPsInsight#56]
I'd like to request a feature:

![bitmap](https://github.com/user-attachments/assets/70d21604-8886-46a1-aebb-d8ad1188982d)

Where the magenta line represents the number of open pull requests/issues, so we can see how we're doing overall with reviewing EIPs.

**Comment by viwinkumarpadala** [comment]
Hey @SamWilsn  ! 👋

- We have added the requested magenta trend line for the number of created PRs/ created Issues each month and even more information than before.
![image](https://github.com/user-attachments/assets/4c079a3b-b410-4b5f-a4a6-c6e1da593bce)

Please check out our website and let us know if it is clear or if we need to update anything.

Thanks again for making the request! 🙏 We really appreciate your contribution. Please continue to share feedback (or)make more requests like this and help us make the website even better! 🚀.

**Comment by SamWilsn** [comment]
So the magenta line is the total number of open issues + open prs?

**Comment by viwinkumarpadala** [comment]
So, Open PRs represent the number of PRs that were still open during that month and the Created PRs are those that have been newly opened in that month. (we are showing both the data in our plots)
- The magenta line represents the PRs created that month. The magenta line in the PRs section represents the number of Created PRs in each month, whereas the magenta line in the Issues section represents the number of Issues created in each month.
- Is that not what you were expecting? If not, then I can try combining the data and make a common magenta line.

**Comment by SamWilsn** [comment]
Er, sorry, I brainfarted there. I should have said: does the magenta line represent the number of open items (PRs on the PRs section, and issues on the issues section)?

---

Honestly, I think I misread the graph the first time I looked at it :sweat_smile:

The legend says "Closed PRs" and "Merged PRs". I interpreted that to mean "the number of pull requests opened/closed/merged during that month."

What I think you're actually showing is the absolute number of each of those items. Is that correct?

---

The checkbox doesn't toggle the line on and off.

**Comment by SamWilsn** [comment]
I'm kinda just noodling here, but what do you think of a graph like this instead:

![eips-insights-graph](https://github.com/user-attachments/assets/082a3f85-2514-4d0a-9338-2d743b876660)

Key features:

 - Single Y-axis
 - Closed/merged items are shown stacked as negative numbers
 - Opened items are show as positive numbers
 - Trend line shows the count of items that remain open at the end of the month.

**Comment by viwinkumarpadala** [comment]
Hey @SamWilsn,
- Yes that is correct, we are showing the absolute numbers of each each of those items.
- I will fix that checkbox bug
- Ya sure, that graph looks great, I will try to check if we can make it that way.

**Comment by poojaranjan** [comment]
I liked the chart suggested by @SamWilsn. Let's see if this can be implemented.

**Comment by viwinkumarpadala** [comment]
@SamWilsn @poojaranjan we have updated the chart on the website, and also cleared the mentioned bug(The trend line is hided now when deselected the checkbox)
![image](https://github.com/user-attachments/assets/3dc51760-735e-4bb8-a754-08ff94dd8277)

**Comment by SamWilsn** [comment]
The label for the magenta line ("Created") is a bit confusing I think? In my example graph, the line indicated the total number of unclosed PRs at the end of the month. Is that how your works?

**Comment by poojaranjan** [comment]
@viwinkumarpadala,  IMO, it will be helpful to document legends clearly on the webpage.  In my mind, useful legends are as below

- Pending = Carried from earlier months
- Created = Created in that particular month
- Closed = Closed in that particular month
- Merged = Merged in that particular month
- Reviewed = Reviewed in that particular month
- Opened = Pending + Created
and Unclosed = Opened - (Closed+Merged) = Pending

I'd think the Magenta line should represent the `Pending` PRs. @SamWilsn please correct me if you're looking at it differently.

**Comment by SamWilsn** [comment]
How about:

 - *Open* - line - the number of items that remain unclosed at the end of the month. Essentially this number:
![image](https://github.com/user-attachments/assets/2c114dc3-76bc-4c9c-9042-59332392faac)
 - *Created* - positive bar - number of items created during the month.
 - *Closed* - negative bar - number of items closed without merging during the month.
 - *Merged* - negative bar - number of items merged during the month.

Reviewed being on the same graph is a bit misleading, since reviewing doesn't decrease the total number of open items.

**Comment by poojaranjan** [comment]
Okay, that make sense. 

I wasn't sure about keeping the "Reviewed" in the Analytics section in the beginning since we have the "Reviewers" tool separately. But, am fine keeping it as an option (enabled with a check box) for people who may be interested in that data.

Having said that, I agree, the legends suggested by @SamWilsn will make more sense for this chart.

**Comment by viwinkumarpadala** [comment]
Yes we have updated the website based on the inputs that you have provided @SamWilsn @poojaranjan.Now we are displaying 4 details:  
![image](https://github.com/user-attachments/assets/003d6f23-fb99-4a0a-b2ae-529017c735b8)
Created - positive bar:  Created in that particular month
Closed - negative bar: number of items closed without merging during the month.
Merged - negative bar: number of items merged during the month.
Open- Magenta line: the number of items that remain unclosed at the end of the month

*Note: The data related to the number of PRs might vary slightly when compared to official github repository due to factors like deleted PRs.*

**Comment by EtherWorldCo** [comment]
Task completed. Please open a new Issue to report any further bug. Thanks!
